spring:
  datasource:
    url: jdbc:mysql://localhost:3306/EGTask?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: EGTaskUser
    password: EGTaskPassword
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    database: mysql
    show-sql=: false
    hibernate:
      ddl-auto: none
    database-platform: rg.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  flyway:
    enabled: true
    baselineOnMigrate: true
    locations: classpath:db/migration
server:
  servlet:
    session:
      timeout: 60